### ISSUE TITLE
Update Jupyterhub version to 1.2.1(latest)

### ISSUE THREAD

**Issue by hemajv** [opendatahub-io/jupyterhub-quickstart#14]
**Is your feature request related to a problem? Please describe.**
The current JupyterHub version
doesn't seem to support some of the [monitoring metrics](https://github.com/jupyterhub/jupyterhub/blob/master/jupyterhub/metrics.py#L38) that have been added and made available in the latest JupyterHub version (1.2.1).

**Describe the solution you'd like**
Update the JupyterHub version to 1.2.1 (latest).

**Describe alternatives you've considered**
None

**Additional context**
We would like to take advantage of these new metrics as it would be useful for our Operate First monitoring purposes. Related issue [here](https://github.com/operate-first/SRE/issues/16).

**Comment by hemajv** [comment]
@vpavlin

**Comment by vpavlin** [comment]
Thanks, we'll take a look at this

**Comment by vpavlin** [comment]
It would be great to review the `requirements.txt` and update everything that needs to be updated.
